"""Utilities to manipulate power duration curves, fit them and do what-if analysis"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_MMP.ipynb.

# %% auto 0
__all__ = ['MMP']

# %% ../nbs/00_MMP.ipynb 4
import numpy as np
import pandas as pd

# %% ../nbs/00_MMP.ipynb 6
class MMP:
    "A Mean Max Power curve"
    def __init__(self
                 , x     # Time
                 , y):   # Power
        self.x, self.y = x, y
    
    def fit(self): pass
        
    
